import { TinWhistleKeys } from "../types/TinWhistleKeys";

export const tinWhistleTabsByKey: TinWhistleKeys = {
  A: {
    "a": { fingers: [1, 1, 1, 1, 1, 1], description: "Low A" },
    "a#": { fingers: [1, 1, 1, 1, 1, 0.5], description: "Low A#" },
    "b": { fingers: [1, 1, 1, 1, 1, 0], description: "Low B" },
    "c": { fingers: [1, 1, 1, 1, 0.5, 0], description: "Low C" },
    "c#": { fingers: [1, 1, 1, 1, 0, 0], description: "Low C#" },
    "d": { fingers: [1, 1, 1, 0, 0, 0], description: "Low D" },
    "d#": { fingers: [1, 1, 0.5, 0, 0, 0], description: "Low D#" },
    "e": { fingers: [1, 1, 0, 0, 0, 0], description: "Low E" },
    "f": { fingers: [1, 0.5, 0, 0, 0, 0], description: "Low F" },
    "f#": { fingers: [1, 0, 0, 0, 0, 0], description: "Low F#" },
    "g": { fingers: [0.5, 0, 0, 0, 0, 0], description: "Low G" },
    "g1": { fingers: [0, 1, 1, 0, 0, 0], description: "Low G1" },
    "g#": { fingers: [0, 0, 0, 0, 0, 0], description: "Low G#" },
    "g#1": { fingers: [0, 0, 0, 0, 0, 1], description: "Low G#1" },
    "a+": { fingers: [0, 1, 1, 1, 1, 1], description: "Middle A" },
    "a#+": { fingers: [1, 1, 1, 1, 1, 0.5], description: "Middle A#" },
    "b+": { fingers: [1, 1, 1, 1, 1, 0], description: "Middle B" },
    "c+": { fingers: [1, 1, 1, 1, 0.5, 0], description: "Middle C" },
    "c#+": { fingers: [1, 1, 1, 1, 0, 0], description: "Middle C#" },
    "d+": { fingers: [1, 1, 1, 0, 0, 0], description: "Middle D" },
    "d#+": { fingers: [1, 1, 1, 0.5, 0, 0], description: "Middle D#" },
    "e+": { fingers: [1, 1, 0, 0, 0, 0], description: "Middle E" },
    "f+": { fingers: [1, 0, 0, 0, 0, 0], description: "Middle F" },
    "f#+": { fingers: [1, 0, 0, 0, 0, 0], description: "Middle F#" },
    "g+": { fingers: [0, 1, 1, 0, 0, 0], description: "Middle G" },
    "g#+": { fingers: [0, 1, 1, 0, 0, 0], description: "Middle G#" },
    "a++": { fingers: [0, 1, 1, 1, 1, 1], description: "High A" },
    "a#++": { fingers: [1, 1, 1, 1, 1, 0.5], description: "High A#" },
    "b++": { fingers: [1, 1, 1, 1, 1, 0], description: "High B" },
    "c++": { fingers: [1, 1, 1, 1, 0.5, 0], description: "High C" },
    "c#++": { fingers: [1, 1, 1, 1, 0, 0], description: "High C#" },
    "d++": { fingers: [1, 1, 1, 0, 0, 0], description: "High D" },
    "d#++": { fingers: [1, 1, 1, 0.5, 0, 0], description: "High D#" },
    "e++": { fingers: [1, 1, 0, 0, 0, 0], description: "High E" },
    "f++": { fingers: [1, 0, 0, 0, 0, 0], description: "High F" },
    "f#++": { fingers: [1, 0, 0, 0, 0, 0], description: "High F#" },
    "g++": { fingers: [0, 1, 1, 0, 0, 0], description: "High G" },
    "g#++": { fingers: [0, 1, 1, 0, 0, 0], description: "High G#" },
  },
  D: {
    d: { fingers: [1, 1, 1, 1, 1, 1], description: "Low D" },
    e: { fingers: [1, 1, 1, 1, 1, 0], description: "Low E" },
    f: { fingers: [1, 1, 1, 1, 0.5, 0], description: "Low F" },
    "f#": { fingers: [1, 1, 1, 1, 0, 0], description: "Low F#" },
    g: { fingers: [1, 1, 1, 0, 0, 0], description: "Low G" },
    a: { fingers: [1, 1, 0, 0, 0, 0], description: "Low A" },
    "a#": { fingers: [1, 0.5, 0, 0, 0, 0], description: "Low A#" },
    b: { fingers: [1, 0, 0, 0, 0, 0], description: "Low B" },
    c: { fingers: [0, 1, 1, 0, 0, 0], description: "Middle C" },
    "c#": { fingers: [0, 0, 0, 0, 0, 0], description: "Middle C#" },
    "d+": { fingers: [0, 1, 1, 1, 1, 1], description: "High D" },
    "e+": { fingers: [1, 1, 1, 1, 1, 0], description: "High E" },
    "f#+": { fingers: [1, 1, 1, 1, 0, 0], description: "High F#" },
    "g+": { fingers: [1, 1, 1, 0, 0, 0], description: "High G" },
    "a+": { fingers: [1, 1, 0, 0, 0, 0], description: "High A" },
    "a#+": { fingers: [1, 0, 1, 0, 0, 0], description: "High A#" },
    "b+": { fingers: [1, 0, 0, 0, 0, 0], description: "High B" },
    "c+": { fingers: [0, 1, 0, 1, 1, 1], description: "High C" },
    "c#+": { fingers: [0, 0, 0, 1, 1, 1], description: "Very High C#" },
    "c#++": { fingers: [0, 0, 0, 0, 0, 0], description: "Very High C#" },
    "d++": { fingers: [0, 1, 1, 1, 1, 1], description: "Very High D" },
    "e++": { fingers: [1, 1, 1, 1, 1, 0], description: "Very High E" },
    "f#++": { fingers: [1, 1, 1, 1, 0, 0], description: "Very High F#" },
    "g++": { fingers: [1, 1, 1, 0, 0, 0], description: "Very High E" },
    "a++": { fingers: [1, 1, 0, 0, 0, 0], description: "Very High A" },
    "b++": { fingers: [1, 0, 0, 0, 0, 0], description: "Very High B" },
  },
  C: {
    c: { fingers: [1, 1, 1, 1, 1, 1], description: "C" },
    d: { fingers: [1, 1, 1, 1, 1, 0], description: "D" },
    e: { fingers: [1, 1, 1, 1, 0.5, 0], description: "E" },
    f: { fingers: [1, 1, 1, 1, 0, 0], description: "F" },
    g: { fingers: [1, 1, 1, 0, 0, 0], description: "G" },
    a: { fingers: [1, 1, 0, 0, 0, 0], description: "A" },
    b: { fingers: [1, 0, 0, 0, 0, 0], description: "B" },
    "c+": { fingers: [0, 1, 0, 0, 0, 0], description: "High C" },
    "c#+": { fingers: [0, 0, 0, 0, 0, 0], description: "High C#" },
    "d+": { fingers: [0, 1, 1, 1, 1, 1], description: "High D" },
    "e+": { fingers: [1, 1, 1, 1, 1, 0], description: "High E" },
    "f#+": { fingers: [1, 1, 1, 1, 0, 0], description: "High F#" },
    "g+": { fingers: [1, 1, 1, 0, 0, 0], description: "High G" },
    "a+": { fingers: [1, 1, 0, 0, 0, 0], description: "High A" },
    "b+": { fingers: [1, 0, 0, 0, 0, 0], description: "High B" },
    "c++": { fingers: [0, 1, 0, 1, 1, 1], description: "Very High C" },
    "d++": { fingers: [0, 0, 0, 0, 0, 0], description: "Very High D" },
    "e++": { fingers: [0, 1, 1, 1, 1, 1], description: "Very High E" },
    "f#++": { fingers: [1, 1, 1, 1, 1, 0], description: "Very High F#" },
    "g++": { fingers: [1, 1, 1, 1, 0, 0], description: "Very High G" },
    "a++": { fingers: [1, 1, 1, 0, 0, 0], description: "Very High A" },
    "b++": { fingers: [1, 1, 0, 0, 0, 0], description: "Very High B" },
  },
};
